addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"          % "0.1.14")
addSbtPlugin("io.spray"                  % "sbt-revolver"          % "0.9.1")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"          % "0.14.10")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"          % "2.4.6")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"          % "0.10.1")
addSbtPlugin("com.alejandrohdezma"       % "sbt-fix"               % "0.7.0")
addSbtPlugin("com.alejandrohdezma"       % "sbt-scalafix-defaults" % "0.9.0")
